<?php
/**
 * WhiteDNSZone Configuration Sample
 * 
 * This file shows example configuration values.
 * Do not edit this file directly - configure through WHMCS admin area.
 */

return [
    // API Configuration
    'api_url' => 'https://my.whitednszone.com/api',
    'api_key' => 'your-api-key-here',
    
    // Default Nameservers
    'default_ns1' => 'dns1.whitednszone.com',
    'default_ns2' => 'dns2.whitednszone.com',
    
    // Feature Flags
    'enable_audit_log' => true,
    'enable_propagation_check' => true,
    
    // Additional Settings
    'default_ttl' => 3600,
    'max_records_per_zone' => 500,
];
